### ISSUE TITLE
Did dependicies change with the new release yesterday.

### ISSUE THREAD

**Issue by actiniumshark12** [vmware-clarity/ng-clarity#1548] opened 2024-09-06 15:22 UTC
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

When I run:
npm install @cds/core @clr/angular @clr/ui --save

I get back:

Installing the clarity modules need for use.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ui@0.0.0
npm ERR! Found: @angular/common@17.3.12
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.3.0" from the root project
npm ERR!   peer @angular/common@"15 || 16 || 17 || 18" from @clr/angular@17.3.0
npm ERR!   node_modules/@clr/angular
npm ERR!     @clr/angular@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^18.0.0 || ^19.0.0" from @angular/cdk@18.2.3
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"15 || 16 || 17 || 18" from @clr/angular@17.3.0
npm ERR!   node_modules/@clr/angular
npm ERR!     @clr/angular@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2024-09-06T13_31_08_740Z-eresolve-report.txt

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Have angular 17 installed
2.  I use nvm to install node.js nvm install v20.17.0
`ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 17.3.9
Node: 20.17.0
Package Manager: npm 10.8.2
OS: linux x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.9
@angular-devkit/build-angular   17.3.9
@angular-devkit/core            17.3.9
@angular-devkit/schematics      17.3.9
@angular/cli                    17.3.9
@schematics/angular             17.3.9
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10`

4.  ng new test --routing --style scss --standalone false --ssr false --interactive false
5.  cd test
6. run npm install @cds/core @clr/angular @clr/ui --save
The errors.
# npm install @cds/core @clr/angular @clr/ui --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ui@0.0.0
npm ERR! Found: @angular/common@17.3.12
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.3.0" from the root project
npm ERR!   peer @angular/common@"15 || 16 || 17 || 18" from @clr/angular@17.3.0
npm ERR!   node_modules/@clr/angular
npm ERR!     @clr/angular@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^18.0.0 || ^19.0.0" from @angular/cdk@18.2.3
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"15 || 16 || 17 || 18" from @clr/angular@17.3.0
npm ERR!   node_modules/@clr/angular
npm ERR!     @clr/angular@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2024-09-06T14_51_00_044Z-eresolve-report.txt

## Expected behavior

When I did basiclly the same yesterday morning I did not see have the errors above. They just started happening this morning. I run a new fresh build steps like above everyday in my ci/cd env.

## Versions

**Clarity version:**

- [ ] v13.x
- [ ] v15.x
- [ X ] Other:
17.3.12 can be seen in the ng version output above.

**Framework version:**
Angular 17.

**Device:**

- Type: [e.g. MacBook]  vmware 8.0 vm
- OS: PRETTY_NAME="Ubuntu 22.04.4 LTS"
- Browser firefox
- Version 130

## Additional notes

When I looked at the version located here 
https://github.com/vmware-clarity/ng-clarity/releases/tag/v17.3.0
looks like a new updated version was released sometime yesterday and it has in the notes
add support for Angular 18

and from the above dependency seems that angular version 18 is required now.

I will assume that this page will be updated soon as well.

https://clarity.design/pages/support-policies

As it doesn't state that 18 is supported yet.

Is Angular version 17 still supported or do I need to go to angular 18 to get around this issue? If so I will assume that Angualr is fully supported now?

Thanks

**Comment by kevinbuhmann** [comment] 2024-09-06 17:22
Do you have `@angular/cdk` installed? That has been a peer dependency since v15. I think that is your issue because 1) your reproduction instructions do not include installing `@angular/cdk` and 2) I get the same error but it works after installing `@angular/cdk`.

**Comment by actiniumshark12** [comment] 2024-09-06 17:31
Hey Kevin,

I will add @angular/cdk to my install and see that all is working.

If that is the case can you please have a look at the following link:

https://clarity.design/pages/developing#installing-the-clarity-htmlcss-framework

It doesn't mention having to have the cdk installed for the an existing angular app. Just has to do the following:

Step 2: Install Clarity Packages

Clarity is published as three separate packages on npm. The names of these packages are shown in the following list:

    @cds/core: The library of web components, design tokens and foundational pieces also used in Angular components.
    @clr/ui: Contains the static styles for building HTML components.
    @clr/angular: Contains the Angular components. This package depends on @clr/ui for styles.

Install all the packages by running the following command with npm:

npm install @cds/core @clr/angular @clr/ui --save

I was able to get it to install the previous version using a command line like the following which will have the version 17.2.1.

npm install @cds/core @clr/angular@17.2.1 @clr/ui@17.2.1 --save

Just a quick workaround to get things back going about to test with the cdk and I will reply back to you after it runs.

Thanks for the the quick reply.

**Comment by kevinbuhmann** [comment] 2024-09-06 17:44
I will update the website pages you've mentioned.

I am not sure why it works without `@angular/cdk` in v17.2.1, but not in v17.3.0. I don't see anything that could have caused that in our changes. It seems like `npm` is automatically installing the `@angular/cdk` peer dependency for v17.2.1, but not for v17.3.0. I am not sure why.

**Comment by actiniumshark12** [comment] 2024-09-06 18:09
I had to use my dev env as I upgraded my test system that I used for all of the above. It has a few behind levels but all for Angular 17 and it still fails with the @angular/cdk on the install line.

npm install @angular/cd @cds/core @clr/angular @clr/ui --save

Giving the exact versions I want still works and also the 17.3.0 works with Angular 18 in my test env.

Thanks for updating the docs I will push on with the using 17.2.1 until I ugrade my env with Angular 18.

Thanks for the help and it is good to know that the new version will support Angualr 18 so will get ready to upgrade to 18.

**Comment by actiniumshark12** [comment] 2024-09-06 18:24
I had missed having the K at the end of @angular/cdk.

Still tested with the install line.
npm install @angular/cdk @cds/core @clr/angular @clr/ui --save

Still the same just an FYI for you.

**Comment by kevinbuhmann** [comment] 2024-09-06 18:52
You probably need to specify for specific Angular version for `@angular/cdk`. It might be trying to install `@angular/cdk@18` into your Angular 17 project.

Using the Angular CLI to install `@angular/cdk` might work better: `ng add @angular/cdk`.

**Comment by actiniumshark12** [comment] 2024-09-06 19:08
Okay thanks Kevin will try to give it @17 and see how it works.

**Comment by actiniumshark12** [comment] 2024-09-06 19:39
Hey Kevin,

Running the following works.

npm install @angular/cdk@17 @cds/core @clr/angular @clr/ui --save

**Comment by kevinbuhmann** [comment] 2024-09-06 20:06
Thanks for the confirmation! I'll close this issue now, but feel free to reopen if needed.

**Closed by kevinbuhmann** 2024-09-06 20:06 UTC
