### ISSUE TITLE
Navigation missing transition animation during mobile view

### ISSUE THREAD

**Issue by lohgyn** [vmware-clarity/ng-clarity#301] opened 2022-08-28 14:46 UTC
## Describe the bug

In the previous version of clarity, there is a transition animation when opening the navigation menu after clicking the hamburger icon during mobile view. It's currently missing in v13 even in the main web page.

## How to reproduce

https://clarity.design/

1.  Click on 'hamburger' icon to open menu, the menu is being open immediately.

## Expected behavior

1. Menu should be opened with the specified transition animation and duration

## Versions

**Clarity version:**

- [ ] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

**Device:**

- Type: Desktop
- OS: Windows 10
- Browser Chrome
- Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by bbogdanov** [comment] 2022-08-29 17:30
Duplicate of #97

**Closed by bbogdanov** 2022-08-29 17:30 UTC
