### ISSUE TITLE
Row does not collapse if expanded row crosses table height (viewport) in Safari

### ISSUE THREAD

**Issue by ruchika0201** [vmware-clarity/ng-clarity#1032] opened 2023-11-03 08:58 UTC
## Describe the bug
On Safari browser, a row once expanded using *clrIfExpanded , it does not collapse if the expanded row crosses the table height (viewport).
This works fine on Chrome browser.

## How to reproduce
[Stackblitz](https://stackblitz.com/edit/issue-expandable-rows-scrolling-5xe2le?file=src%2Fapp%2Fapp.component.html)

Steps to reproduce the behaviour:

1.  On Safari browser, click on caret icon to expand the row.
2.  Click on caret icon again to collapse it.
3.  Notice the issue that the row is not getting collapsed.

## Expected behavior
The row should get collapsed on Safari as well, as on Chrome.

## Versions

**Clarity version:**

   - @clr/angular: 13.11.0
   - @clr/ui: 13.11.0

**Framework version:**

Angular 14

**Device:**

- Type:Macbook
- OS: iOS
- Browser: Safari
- Version: [e.g. 22]

**Comment by kanthvallampati** [comment] 2024-02-09 04:26
Hi @ruchika0201,

I'm pleased to hear that the fix I suggested is successfully addressing your use case. As we discussed, implementing overrides can lead to conflicts with the component's intended behavior, which is likely the cause of the reported issue. It's advisable to refrain from such overrides and rely on the component's native functionality.

We'll keep the issue open for another week to allow for any further discussion or clarification you may need. After that, we'll proceed with closing the issue. Looking forward to hearing from you.

**Comment by kanthvallampati** [comment] 2024-02-23 09:41
Hi @ruchika0201,

We're closing this issue as discussed. If you encounter any further difficulties with the DataGrid (or) any other component, please feel free to open a new issue.

**Closed** 2024-02-23 09:41 UTC
Labels: workaround
