### ISSUE TITLE
Spinner broken in v13

### ISSUE THREAD

**Issue by liebehentze** [vmware-clarity/ng-clarity#406] opened 2022-11-30 08:20 UTC
## Describe the bug
Spinner is not shown in v13, v12 is working, using class spinner.
_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce
Can be seen/reproduced on the documentation site (https://clarity.design/documentation/spinners#top).

## Expected behavior
Working as in v12 (https://v12.clarity.design/documentation/spinners)

## Versions
v13.x

**Comment by Jinnie** [comment] 2022-11-30 08:31
Duplicate of #362, which is already fixed and waiting to be released.

**Closed by Jinnie** 2022-11-30 08:31 UTC
Labels: closed:duplicate
