### ISSUE TITLE
ClrNavLevel closes on .nav-link click even on large screens

### ISSUE THREAD

**Issue by michaelbromley** [vmware-clarity/ng-clarity#89] opened 2022-04-20 08:40 UTC
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

When using the sidenav component with the `[clr-nav-level]="2"` directive, the sidenav will close even when using a desktop browser on the larger breakpoint. This is a change that I think was introduced with this commit: https://github.com/vmware-clarity/ng-clarity/commit/af6c44ce23b47514c15dec60f1db07134cf62f1a. Prior to this, the sidenav would remain open after clicking nav items, and would only close when on small screens with the fly-out version of the menu.

The only way to get the sidenav to return then is to resize the viewport or refresh the page.

## How to reproduce

Stackblitz reproduction: https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-y6zxq4?file=src%2Fapp%2Fapp.component.html

https://user-images.githubusercontent.com/6275952/164187261-d23bdb86-55fe-4f28-993c-2884a3b6d929.mp4

Set up sidenav as in the Stackblitz demo:

```html
<div class="main-container">
  <header class="header-2">
    <div class="branding">
      <a class="nav-link">
        <span class="title">Clarity</span>
      </a>
    </div>
    <div class="header-nav">
      <a class="active nav-link nav-text">Home</a>
    </div>
  </header>
  <div class="content-container">
    <nav class="sidenav" [clr-nav-level]="2">
      <ul class="nav-list">
        <a class="nav-link">Link 1</a>
        <a class="nav-link">Link 2</a>
        <a class="nav-link active">Link 3</a>
        <a class="nav-link">Link 4</a>
        <a class="nav-link">Link 5</a>
        <a class="nav-link">Link 6</a>
        <a class="nav-link">Link 7</a>
        <a class="nav-link">Link 8</a>
        <a class="nav-link active">Link 9</a>
        <a class="nav-link">Link 10</a>
      </ul>
    </nav>
    <div class="content-area">
      <h3>Content</h3>
    </div>
  </div>
</div>
```

Click any of the sidenav links and see that the sidenav closes.

## Expected behavior

It should stay open on large screens and only close for mobile breakpoints. This is how it worked up until (I think) [v12.0.14](https://github.com/vmware-clarity/ng-clarity/releases/tag/v12.0.14)

## Versions

**Clarity version:**

- [x] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Device:**

- Type: [Laptop]
- OS: [Win 10]
- Browser [Brave (Chromium)]
- Version [100]

**Comment by michaelbromley** [comment] 2022-04-20 18:26
Wow fast resolution! Thanks team 👍

**Comment by krnhotwings** [comment] 2022-04-25 19:54
Hi folks! I just came across this bug and tried testing in 13.2.1, but it appears that the bug is not _entirely_ fixed.

The menu will disappear if you set the window's width between MEDIUM_BREAKPOINT and LARGE_BREAKPOINT:

- MEDIUM_BREAKPOINT (768px) < current width < LARGE_BREAKPOINT (992px)
  - sidenav hidden
  - hamburger menu hidden
  - Behavior NOT expected
  - Resize event within this width range triggers appearance of sidenav only; however, clicking on a link causes menu to disappear. Resizing will make sidenav reappear

For widths outside this range, the sidenav behaves as expected:

- current width <= MEDIUM BREAKPOINT
  - sidenav hidden
  - hamburger menu visible
  - hamburger menu functionality works as expected
- current_width >= LARGE_BREAKPOINT
  - sidenav visible
  - hamburger menu invisible
  - sidenav links work properly

I took a peak at the file where the fix was committed:

https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/layout/nav/nav-level.ts

I think problem is due to responsiveness triggering _at or below 768px_ (`MEDIUM_BREAKPOINT`,) so the problem is twofold:

1. All references to `LARGE_BREAKPOINT` should be changed to `MEDIUM_BREAKPOINT` (the point at which the hamburger menu gets drawn)
2. In relation to `MEDIUM_BREAKPOINT`, `<` should be changed to `<=`
3. (Bonus) The [Responsive Navigation doc](https://angular.clarity.design/documentation/navigation) states that `Responsiveness is triggered below the 768px breakpoint`; however, since responsiveness triggers at or below 768px, the documentation should be updated to reflect this nuance.

**Comment by bbogdanov** [comment] 2022-05-04 13:07
Closing in favour of #97

**Closed by bbogdanov** 2022-05-04 13:07 UTC
Labels: released, released on @12.x
